// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoejrfmbrccczgsmsgen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZWpyZm1icmNjY3pnc21zZ2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjQyMTksImV4cCI6MjA2NTYwMDIxOX0.PMF55J2MeRmxCiN8Iq-Qo2u-PJOp4vlls57oAC8Xbrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);